// src/components/link.tsx
export default function Link({ href, children }: { href: string; children: React.ReactNode }) {
    return (
        <a
            className="text-primary-background border-[1px] p-1 rounded-md hover:bg-foreground/10 duration-250"
            href={href}
            target="_blank"
            rel="noopener noreferrer"
        >{children}</a>
    );
}

// src/components/Link.vue
<script setup lang="ts">
const props = defineProps<{
    to: string;
}>();
</script>

<template>
    <a
        class="link tr flex flex-row gap-x-0.5rem justify-start items-center text-mode-900"
        :href="props.to"
        target="_blank"
        rel="noopener noreferrer"
    >
        <i-carbon-arrow-up-right/>
        <slot/>
    </a>
</template>
